appName:  servicename
appImage: gcr.io/google-samples/microservices-demo/servicename
appVersion: v0.0.0
appReplicas:  1
containerPort:  8080
containerEnvVars: 
- name: ENV_VAR_ONE
  value:  "valueone"

servicePort:  8080
serviceType:  ClusterIP
targetPort: 8000
